version: "3.9"

networks:
  employee-net:
    driver: bridge

volumes:
  mysql-data:

services:
  app:
    build: .
    image: employee-service-optimized:1.0
    container_name: employee-service
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - employee-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/employeedb
      SPRING_DATASOURCE_USERNAME: employee
      SPRING_DATASOURCE_PASSWORD: employee123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true

  mysql:
    image: mysql:8.0
    container_name: mysql
    networks:
      - employee-net
    environment:
      MYSQL_DATABASE: employeedb
      MYSQL_USER: employee
      MYSQL_PASSWORD: employee123
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - mysql-data:/var/lib/mysql
